### ISSUE TITLE
Installation of any python package fails

### ISSUE THREAD

**Issue by Kaffeegangster** [microsoft/sqlmlutils#45]
Trying to install a python package on SQL2017 always fails with "Incorrect syntax near 'Python'"
e.g. 
..
sqlmlutils.SQLPackageManager(connection).install("tensorflow")

fails with this exception:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\sqlmlutils\sqlqueryexecutor.py", line 44, in execute
    self._mssqlconn.execute_query(builder.base_script, builder.params)
  File "src\_mssql.pyx", line 1064, in _mssql.MSSQLConnection.execute_query
  File "src\_mssql.pyx", line 1095, in _mssql.MSSQLConnection.execute_query
  File "src\_mssql.pyx", line 1228, in _mssql.MSSQLConnection.format_and_run_query
  File "src\_mssql.pyx", line 1639, in _mssql.check_cancel_and_raise
  File "src\_mssql.pyx", line 1683, in _mssql.maybe_raise_MSSQLDatabaseException
_mssql.MSSQLDatabaseException: (102, b"Incorrect syntax near 'Python'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

It seems that the python script created by class CreateLibraryBuilder is invalid.

**Comment by JonathanZhu11** [comment]
Python package management isn't supported in SQL2017, only 2019 CTP2.4 onwards:

https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-library-transact-sql?view=sql-server-2017

> 
>  Note
> In SQL Server 2017, R language and Windows platform are supported. R, Python, and external languages on the Windows and Linux platforms are supported in SQL Server 2019 CTP 2.4 and later.

**Comment by ivangvi** [comment]
> Python package management isn't supported in SQL2017, only 2019 CTP2.4 onwards:
> 
> https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-library-transact-sql?view=sql-server-2017
> 
> > Note
> > In SQL Server 2017, R language and Windows platform are supported. R, Python, and external languages on the Windows and Linux platforms are supported in SQL Server 2019 CTP 2.4 and later.

Are there any plans on bringing support of Python package installation for SQL Server 2017 in the near future?

**Comment by JonathanZhu11** [comment]
There are no plans to backport new features to older releases - updates in SQL Server 2017 are only for bug fixes.

**Comment by ivangvi** [comment]
Thank you @JonathanZhu11 , actually I stumbled upon this issue while trying to install packages on SQL Server 2017, wrongly following SQL Server 2019's documentation. That's why I was struggling with pymssql and sqlmlutils, while I only needed to use the pip.exe located under my installation folder.

This is the doc that I was supposed to be reading: https://docs.microsoft.com/en-us/sql/machine-learning/package-management/install-python-packages-standard-tools?view=sql-server-2017

Maybe something could be clarified on 2019's doc or somewhere else, regarding 'if you have Server 2017', because somehow I ended up being convinced I needed to make pymssql + sqlmlutils work in order to install packages.
